spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easyproject?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    initialPoolSize: 20
    minPoolSize: 5
    maxPoolSize: 100

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliase-package: com.sxxy.sportplay.dao

server:
  port: 8787
